= vscode-shards

Shards Language Support in VSCode

The "vscode-shards" extension will provide comprehensive support for the Shards programming language in Visual Studio Code. Developed in ClojureScript, the extension will offer:

* [ ] syntax highlighting
* [x] Go to definitions
* [ ] Go to references
* [ ] Outline

== Install extension

Grab it from the link:https://marketplace.visualstudio.com/items?itemName=fragcolor.shards[VS Code Marketplace], or issue the command:
```
code --install-extension fragcolor.shards
```
You could also copy this repo to `<user home>/.vscode/extensions` folder and restart VS Code.

== Usage

After installing the extension, open any `.shs` file to activate the extension.

==  Development

Development using shadow-cljs and VS Code debugger.

Install https://shadow-cljs.github.io/docs/UsersGuide.html#_installation[shadow-cljs] command globally and local npm dependencies:
[code, bash]
----
npm install -g shadow-cljs
npm install
----

Compile:
[code, bash]
----
shadow-cljs watch dev
----

=== Debug extension

Start debugging this extension:

1. In command palette: (Debug *->* Start Debugging) 
2. When asked, select "Node.js" and `:dev` build

At this point you can test features like go to definition e.g., in the provided `test.shs` file.

=== Publish this extension

Bump the `version` number in `package.json` before publishing this extension.

=== Extension code

In the `extension.core` namespace we have a function called `activate`. In it we tell vscode to run a function when the extension is activated. 

To re-run `activate`, click the green `Restart`-symbol in the debugging interface (the one with the pause-button etc).

Make sure that your project compiles properly, you see this by looking in the terminal, where `shadow-cljs` is nice enough to tell you when something goes wrong.

==== But what about the REPL?

We're lucky to have https://github.com/thheller[thheller] provide for us. When you run `shadow-cljs watch dev`, you might notice the following in the terminal: `shadow-cljs - nREPL server started on port 61155`. Great news!

1. Connect to the nREPL server using your favourite client. Since you're using vscode, maybe https://marketplace.visualstudio.com/itemdetails?itemName=cospaia.clojure4vscode[Calva]? I've also tried https://cider.readthedocs.io/en/latest/[cider-mode]. Calva was the most simple though, so I recommend that.
2. Now, you might think that you can just fire away stuff like `(js/console.log "I'm the queen!")`, but sadly, your client will most likely just get mad at you. This is what I got:
   ```
   Syntax error compiling at (cljs-vscode-extension-hello-world:localhost:62584(clj)*<2>:47:14).
   No such namespace: js
   ```
   The issue? We're in jvm-land!
   
==== We need to go deeper!
To go to CLJS-land, I found it easiest to:

1. Stop debugging
2. Add a dependency to `shadow-cljs.edn`:
    ```clojure
    :dependencies
    [[cider/cider-nrepl "0.21.0"]]
    ```
3. Write the following in a terminal (if in VSCode, preferably the one you start debugging from):
    ```bash
    $ shadow-cljs clj-repl
    => (shadow/watch :dev)
    => (shadow/repl :dev)
    ```
    With log messages, it will look something like this (note the nREPL port, you'll need it later):
    ```bash
    $ shadow-cljs clj-repl
    shadow-cljs - config: <...>/cljs-vscode-extension-hello-world/shadow-cljs.edn  cli version: 2.8.29  node: v8.15.0
    shadow-cljs - server version: 2.8.29 running at http://localhost:9630
    shadow-cljs - nREPL server started on port 55618
    shadow-cljs - REPL - see (help)
    To quit, type: :repl/quit
    [1:0]~shadow.user=> (shadow/watch :dev)
    [:dev] Configuring build.
    [:dev] Compiling ...
    [:dev] Build completed. (42 files, 2 compiled, 0 warnings, 3.45s)
    :watching
    [1:0]~shadow.user=> (shadow/repl :dev)
    [1:1]~cljs.user=>
    ```
    If you now try to eval something in your fresh cljs-repl, you'll might get an error such as: `No application has connected to the REPL server. Make sure your JS environment has loaded your compiled ClojureScript code.`

4. Start debugging again
5. Run the "Hello World" command (this loads your code into vscode)
6. Try evaling something at the cljs-repl in the terminal again. Now it should work. :)

==== Now add the finishing strokes

1. Connect using your favourite repl client, e.g. https://marketplace.visualstudio.com/itemdetails?itemName=cospaia.clojure4vscode[Calva] or https://cider.readthedocs.io/en/latest/[cider-mode].
2. Assuming Calva, you can use the command "Calva: Connect", either in the debugging instance (for that emacs feeling), or in the vscode instance that started debugging.
3. It's important that you fill in the port you got from running `shadow-cljs clj-repl` before.
4. Choose `:dev` when asked about build
5. When you have successfully connected with a cljs-repl client, you should be able to evaluate: `(js/console.log "I'm the queen!")` - the result is shown in the `Debug Console` of the vscode instance where you started debugging!
6. To really verify that it works, you could run the following in the repl:
```clojure
(in-ns 'extension.core) ;;=> extension.core
```
A notification should popup in the vscode instance running the plugin.

More information about shadow-cljs: https://shadow-cljs.github.io/docs/UsersGuide.html

If you try this in `cider-mode`, it's important to **not** press enter when connecting using the sibling repl. You have to explicitly write `:dev`. If you don't understand what I mean about sibling repl, check the shadow-cljs docs above.

== Contributing

Contributions are welcome! Feel free to open an issue or submit a pull request.

To share this extension with the world, read on about https://code.visualstudio.com/api/working-with-extensions/publishing-extension[publishing an extension].

== link:LICENSE[License]

_vscode-shards-syntax_ source code is licensed under the link:./LICENSE[BSD 3-Clause license].
